"""add graph_layer_styles table

Revision ID: 2cb8d0cb303a
Revises: 1d7789a07149
Create Date: 2025-12-10 22:29:35.326362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cb8d0cb303a'
down_revision = '1d7789a07149'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph_layer_styles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('layer', sa.Integer(), nullable=False),
    sa.Column('node_color', sa.String(length=16), nullable=False),
    sa.Column('border_color', sa.String(length=16), nullable=False),
    sa.Column('shape', sa.String(length=16), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('graph_layer_styles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_graph_layer_styles_layer'), ['layer'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('graph_layer_styles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_graph_layer_styles_layer'))

    op.drop_table('graph_layer_styles')
    # ### end Alembic commands ###
